// <auto-generated />
using AssignmentBackEnd1.DatabaseHelper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AssignmentBackEnd1.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220128213656_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AssignmentBackEnd1.DatabaseHelper.MyDbContext+Produce", b =>
                {
                    b.Property<int>("ProduceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProduceID");

                    b.ToTable("Produces");

                    b.HasData(
                        new
                        {
                            ProduceID = 1,
                            Description = "Oranges"
                        },
                        new
                        {
                            ProduceID = 2,
                            Description = "Apples"
                        },
                        new
                        {
                            ProduceID = 3,
                            Description = "Peaches"
                        });
                });

            modelBuilder.Entity("AssignmentBackEnd1.DatabaseHelper.MyDbContext+ProduceSupplier", b =>
                {
                    b.Property<int>("ProduceID")
                        .HasColumnType("int");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("ProduceID", "SupplierID");

                    b.HasIndex("SupplierID");

                    b.ToTable("ProduceSuppliers");

                    b.HasData(
                        new
                        {
                            ProduceID = 1,
                            SupplierID = 1,
                            Qty = 25
                        },
                        new
                        {
                            ProduceID = 2,
                            SupplierID = 2,
                            Qty = 12
                        },
                        new
                        {
                            ProduceID = 3,
                            SupplierID = 1,
                            Qty = 30
                        });
                });

            modelBuilder.Entity("AssignmentBackEnd1.DatabaseHelper.MyDbContext+Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierID = 1,
                            SupplierName = "Kin's Market"
                        },
                        new
                        {
                            SupplierID = 2,
                            SupplierName = "Fresh Street Market"
                        });
                });

            modelBuilder.Entity("AssignmentBackEnd1.DatabaseHelper.MyDbContext+ProduceSupplier", b =>
                {
                    b.HasOne("AssignmentBackEnd1.DatabaseHelper.MyDbContext+Produce", "Produce")
                        .WithMany("ProduceSuppliers")
                        .HasForeignKey("ProduceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssignmentBackEnd1.DatabaseHelper.MyDbContext+Supplier", "Supplier")
                        .WithMany("ProduceSuppliers")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produce");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("AssignmentBackEnd1.DatabaseHelper.MyDbContext+Produce", b =>
                {
                    b.Navigation("ProduceSuppliers");
                });

            modelBuilder.Entity("AssignmentBackEnd1.DatabaseHelper.MyDbContext+Supplier", b =>
                {
                    b.Navigation("ProduceSuppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
